// This file will be generated by FlutterFire CLI after Firebase setup.
// Run: dart pub global activate flutterfire_cli
// Then: flutterfire configure
// 
// PLACEHOLDER - Replace with actual generated file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVtwgsR_zsiAzv8kCAOGBlgtZmUHSVRzA',
    appId: '1:742784357743:web:614e041176b0164c80449a',
    messagingSenderId: '742784357743',
    projectId: 'campus-connect-a6aa5',
    authDomain: 'campus-connect-a6aa5.firebaseapp.com',
    databaseURL: 'https://campus-connect-a6aa5-default-rtdb.firebaseio.com',
    storageBucket: 'campus-connect-a6aa5.firebasestorage.app',
  );

  // ⚠️ REPLACE THESE WITH YOUR ACTUAL VALUES FROM FIREBASE CONSOLE

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALe66hmaOIqX4L2Ij1zgVpUXYBSCbjEZc',
    appId: '1:742784357743:android:abd9b03e877ede9d80449a',
    messagingSenderId: '742784357743',
    projectId: 'campus-connect-a6aa5',
    databaseURL: 'https://campus-connect-a6aa5-default-rtdb.firebaseio.com',
    storageBucket: 'campus-connect-a6aa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkxy164gWqTDd_PtAMmvJIlaD-CS63Z4Y',
    appId: '1:742784357743:ios:a4a9ba5edeac733f80449a',
    messagingSenderId: '742784357743',
    projectId: 'campus-connect-a6aa5',
    databaseURL: 'https://campus-connect-a6aa5-default-rtdb.firebaseio.com',
    storageBucket: 'campus-connect-a6aa5.firebasestorage.app',
    iosBundleId: 'com.saveetha.campusConnect',
  );

}